services:
  - type: web
    name: blablabook-api
    runtime: node
    region: frankfurt
    plan: free
    autoDeploy: false
    buildCommand: cd backend && npm install --include=dev
    startCommand: cd backend && npm run build && npm run seed && node dist/src/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
