services:
  - type: web
    name: blablabook-api
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: cd backend && npm install --include=dev && npm run build
    postBuildCommand: cd backend && npm run seed
    startCommand: cd backend && node dist/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
