import { db } from './db';
import { category, keyword, book } from './db/schema';
import { eq } from 'drizzle-orm';

// Compute OpenLibrary cover URL from ISBN (guaranteed to match the correct book)
const coverFromIsbn = (isbn: string): string =>
  `https://covers.openlibrary.org/b/isbn/${isbn.replace(/-/g, '')}-L.jpg`;

// Catégories
const CATEGORIES = [
  { name: 'unknown', isActive: true },
  { name: 'horreur', isActive: true },
  { name: 'romance', isActive: true },
  { name: 'aventure', isActive: true },
  { name: 'fantasy', isActive: true },
  { name: 'science-fiction', isActive: true },
  { name: 'mystère', isActive: true },
  { name: 'thriller', isActive: true },
];

// Keywords par catégorie (liste complète, tous mots-clés fusionnés)
const KEYWORDS_BY_CATEGORY: Record<string, string[]> = {
  horreur: [
    'horror',
    'scary',
    'terror',
    'haunted',
    'supernatural',
    'creepy',
    'dark',
    'evil',
    'curse',
    'monster',
    'ghost',
    'zombie',
    'vampire',
    'possessed',
    'psycho',
    'gore',
    'blood',
    'death',
    'murder',
    'killer',
    'horror fiction',
    'horror stories',
    'occult',
    'paranormal',
    'nightmare',
    'demon',
    'demonic',
    'possession',
    'exorcism',
    'slasher',
    'serial killer',
    'macabre',
    'fear',
    'frightening',
    'body horror',
    'psychological horror',
    'folk horror',
    'gothic horror',
    'haunting',
    'cannibal',
    'werewolf',
    'undead',
    'eldritch',
    'cosmic horror',
    'apocalypse horror',
    'survival horror',
    'satanic',
    'ritual',
    'haunted house',
    'monster fiction',
    'horror novel',
    'creature feature',
    'terrifying',
    'sinister',
    'dreadful',
    'chilling',
    'eerie',
    'spooky',
    'disturbing',
    'gruesome',
    'terrifying creature',
    'night terror',
    'scary story',
    'horror tale',
    'frightful',
    'grotesque',
    'haunted mansion',
    'cursed object',
    'supernatural being',
    'malevolent',
    'sinister force',
    'dark magic',
    'evil spirit',
    'restless spirit',
    'vengeful ghost',
    'creepy atmosphere',
    'psychological terror',
    'unsettling',
    'horrifying',
    'terrifying tale',
    'spine-tingling',
    'blood-curdling',
    'unnatural',
    'unholy',
    'accursed',
    'damned',
    'infernal',
    'nightmarish',
    'phantasmal',
    'spectral',
    'ghostly apparition',
    'malicious spirit',
    'tormented soul',
    'trapped spirit',
    'cursed soul',
    'doomed fate',
    'twisted fate',
    'dark destiny',
    'evil curse',
    'blood curse',
    'death curse',
    'ancient curse',
    'family curse',
    'village curse',
    'town curse',
    'object curse',
    'person curse',
    'cursed bloodline',
    'cursed family',
    'cursed place',
    'cursed forest',
    'cursed mansion',
    'cursed cemetery',
    'cursed house',
    'creepy forest',
    'dark forest',
    'forbidden forest',
    'deep forest',
    'ancient forest',
    'haunted forest',
    'evil forest',
    'monster forest',
    'creature woods',
    'creature forest',
    'creature dwelling',
    'monster lair',
    'beast lair',
    'predator',
    'apex predator',
    'vampire lord',
    'vampire king',
    'vampire queen',
    'werewolf pack',
    'werewolf alpha',
    'zombie horde',
    'undead army',
    'skeleton army',
    'ghost army',
    'demon army',
    'creature swarm',
    'tentacle',
    'tentacles',
    'tentacled',
    'shapeshifter',
    'entity',
    'being',
    'creature',
    'abomination',
    'monstrosity',
    'aberration',
    'abhorrent',
    'vile creature',
    'foul creature',
    'wretched creature',
    'twisted creature',
    'mutated creature',
    'deformed creature',
    'hideous creature',
    'repulsive creature',
    'repugnant',
    'horrific',
    'ghastly',
    'appalling',
    'abysmal',
    'infernal being',
    'hellish creature',
    'demonic entity',
    'satanic entity',
    'evil entity',
    'dark entity',
    'malevolent entity',
    'hostile entity',
    'lethal',
    'deadly',
    'lethal threat',
    'mortal threat',
    'existential threat',
    'annihilation',
    'destruction',
    'obliteration',
    'extinction',
    'apocalypse',
    'end times',
    'doomsday',
    'armageddon',
    'catastrophe',
    'calamity',
    'plague',
    'pestilence',
    'disease',
    'infection',
    'contagion',
    'virus',
    'biological horror',
    'medical horror',
    'body horror',
    'mutation horror',
    'transformation horror',
    'degradation',
    'decay',
    'decomposition',
    'rotting',
    'putrefaction',
    'necrosis',
    'death imagery',
    'skull',
    'skeleton',
    'bones',
    'corpse',
    'cadaver',
    'remains',
    'grave',
    'tomb',
    'crypt',
    'mausoleum',
    'mortuary',
    'funeral',
    'burial',
    'cremation',
    'afterlife',
    'underworld',
    'hell',
    'abyss',
    'void',
    'darkness',
    'shadow',
    'shadows',
    'shadowy',
    'murky',
    'gloomy',
    'dreary',
    'dismal',
    'bleak',
    'desolate',
    'deserted',
    'abandoned',
    'derelict',
    'ruins',
    'rubble',
    'decay',
    'decaying',
    'deteriorating',
    'neglected',
    'overgrown',
    'moss-covered',
    'vine-covered',
    'spider web',
    'cobwebs',
    'dust',
    'dusty',
    'moldy',
    'stale',
    'rancid',
    'foul smell',
    'stench',
    'putrid',
    'nauseating',
    'disgusting',
    'repulsive smell',
    'dread',
    'dreadful',
    'foreboding',
    'ominous',
    'portentous',
    'inauspicious',
    'unlucky',
    'cursed luck',
    'bad omen',
    'ill omen',
    'sign of evil',
    'harbinger',
    'herald of doom',
    'messenger of death',
    'grim reaper',
    'death personified',
    'death incarnate',
    'angel of death',
    'angel of darkness',
    'fallen angel',
    'demon lord',
    'sith lord',
    'dark lord',
    'dark master',
    'dark overlord',
    'tyrant',
    'despot',
    'dictator',
    'oppressor',
    'enslaver',
    'tormentor',
    'torturer',
    'sadist',
    'masochist',
    'insane',
    'insanity',
    'madness',
    'lunacy',
    'psychotic',
    'deranged',
    'unhinged',
    'unstable',
    'fractured mind',
    'broken mind',
    'twisted mind',
    'warped mind',
    'corrupted mind',
    'possessed mind',
    'mind control',
    'brainwashing',
    'hypnosis',
    'mind game',
    'mental torture',
    'psychological abuse',
    'trauma',
    'ptsd',
    'nightmares',
    'sleep paralysis',
    'hallucination',
    'delusion',
    'phantom',
    'apparition',
  ],

  romance: [
    'love',
    'romance',
    'passionate',
    'relationship',
    'couple',
    'heart',
    'emotion',
    'feelings',
    'romance novel',
    'happy ending',
    'destiny',
    'soulmate',
    'chemistry',
    'attraction',
    'intimate',
    'tender',
    'yearning',
    'longing',
    'affection',
    'beloved',
    'romantic',
    'romantic fiction',
    'romantic novel',
    'contemporary romance',
    'historical romance',
    'new adult',
    'young adult romance',
    'slow burn',
    'enemies to lovers',
    'friends to lovers',
    'second chance romance',
    'forbidden love',
    'marriage of convenience',
    'first love',
    'romantic suspense',
    'heartbreak',
    'reunion',
    'wedding',
    'dating',
    'courtship',
    'breakup',
    'devotion',
    'desire',
    'flirt',
    'drama romantique',
    'histoire d amour',
    'romance contemporaine',
    'romance historique',
    'triangle amoureux',
    'romance paranormale',
    'chick lit',
    'feel good romance',
    'sweet romance',
    'steamy romance',
    'emotional connection',
    'love story',
    'romantic tension',
    'passionate love',
    'deep connection',
    'true love',
    'romantic hero',
    'romantic heroine',
    'love triangle',
    'romantic conflict',
    'emotional journey',
    'touching love story',
    'romantic adventure',
    'love conquest',
    'romantic promise',
    'love at first sight',
    'rekindled love',
    'forbidden romance',
    'cross-cultural romance',
    'paranormal romance',
    'vampire romance',
    'werewolf romance',
    'witch romance',
    'fated mates',
    'soul bonding',
    'soulmate connection',
    'destined love',
    'fated love',
    'cosmic love',
    'eternal love',
    'undying love',
    'timeless love',
    'love transcends',
    'transcendent love',
    'passionate embrace',
    'tender embrace',
    'loving embrace',
    'romantic kiss',
    'first kiss',
    'passionate kiss',
    'stolen kiss',
    'kiss in the rain',
    'kiss under the stars',
    'moonlit kiss',
    'beach kiss',
    'sunset kiss',
    'sunrise kiss',
    'midnight kiss',
    'dusk kiss',
    'twilight kiss',
    'romance in the rain',
    'romance under moonlight',
    'romance by firelight',
    'romance by candlelight',
    'romance by starlight',
    'romance in spring',
    'romance in summer',
    'romance in autumn',
    'romance in winter',
    'spring romance',
    'summer romance',
    'autumn romance',
    'winter romance',
    'love blooming',
    'blooming romance',
    'flowering romance',
    'flourishing love',
    'blossoming love',
    'developing romance',
    'growing love',
    'strengthening love',
    'deepening love',
    'intensifying love',
    'overwhelming love',
    'all-consuming love',
    'all-encompassing love',
    'complete love',
    'whole love',
    'unconditional love',
    'selfless love',
    'sacrificial love',
    'protective love',
    'possessive love',
    'jealous love',
    'obsessive love',
    'adoring love',
    'worshiping love',
    'reverent love',
    'respectful love',
    'honorable love',
    'noble love',
    'heroic love',
    'courageous love',
    'brave love',
    'daring love',
    'risky love',
    'dangerous love',
    'perilous love',
    'ill-fated love',
    'star-crossed love',
    'doomed love',
    'tragic love',
    'bittersweet love',
    'melancholic love',
    'wistful love',
    'nostalgic love',
    'haunting love',
    'lingering love',
    'unforgettable love',
    'memorable love',
    'significant love',
    'meaningful love',
    'purposeful love',
    'intentional love',
    'deliberate love',
    'chosen love',
    'willing love',
    'consensual love',
    'mutual love',
    'reciprocal love',
    'requited love',
    'unrequited love',
    'secret love',
    'hidden love',
    'forbidden attraction',
    'dangerous attraction',
    'irresistible attraction',
    'magnetic attraction',
    'compelling attraction',
    'undeniable attraction',
    'unavoidable attraction',
    'chemistry explosion',
    'sparks flying',
    'electricity between them',
    'electric chemistry',
    'explosive passion',
    'wild passion',
    'untamed passion',
    'raw passion',
    'pure passion',
    'genuine passion',
    'authentic passion',
    'real passion',
    'sincere passion',
    'heartfelt passion',
    'soul-deep passion',
    'body and soul',
    'heart and soul',
    'mind and soul',
    'complete surrender',
    'total surrender',
    'vulnerability',
    'emotional vulnerability',
    'exposure',
    'exposure of heart',
    'opening up',
    'letting down walls',
    'breaking barriers',
    'overcoming obstacles',
    'fighting for love',
    'fighting against odds',
    'defying convention',
    'defying family',
    'defying society',
    'defying fate',
    'love conquers all',
    'love prevails',
    'love wins',
    'love triumphs',
    'love endures',
    'love survives',
    'love persists',
    'love remains',
    'love forever',
    'eternal devotion',
    'lifelong commitment',
    'forever promise',
    'forever vow',
    'forever pledge',
    'till death do us part',
    'beyond death',
    'across time',
    'across distance',
    'across worlds',
    'across dimensions',
    'parallel universe romance',
    'time travel romance',
    'alternate timeline romance',
    'multiverse romance',
    'interdimensional romance',
    'cosmic romance',
    'universal love',
    'transcendent romance',
  ],

  aventure: [
    'adventure',
    'quest',
    'journey',
    'explore',
    'exploration',
    'treasure',
    'discovery',
    'danger',
    'risk',
    'action',
    'thrilling',
    'expedition',
    'survival',
    'challenge',
    'daring',
    'brave',
    'heroic',
    'wild',
    'nature',
    'adventure travel',
    'adventure fiction',
    'sea adventure',
    'pirates',
    'wilderness',
    'expedition fiction',
    'travel',
    'voyage',
    'island',
    'jungle',
    'mountain',
    'explorer',
    'hero',
    'heroine',
    'odyssey',
    'sea voyage',
    'naval adventure',
    'historical adventure',
    'swashbuckling',
    'coming of age adventure',
    'adventure stories',
    'quest fantasy',
    'road trip',
    'trek',
    'perseverance',
    'hunt',
    'escape adventure',
    'rescue mission',
    'dangerous mission',
    'exploration fiction',
    'epic journey',
    'adventure novel',
    'action packed',
    'thrilling adventure',
    'daring escape',
    'perilous journey',
    'brave hero',
    'heroic journey',
    'epic adventure',
    'grand adventure',
    'exciting quest',
    'exotic location',
    'international adventure',
    'outdoor adventure',
    'wilderness adventure',
    'ocean adventure',
    'desert adventure',
    'mountain climbing',
    'expedition story',
    'treasure hunt',
    'lost city',
    'ancient ruins',
    'archaeological adventure',
    'exploration of unknown',
    'brave adventurer',
    'courageous hero',
    'daring feat',
    'impossible mission',
    'against the odds',
    'survival story',
    'danger and excitement',
    'thrilling experience',
    'action adventure',
    'adventure filled',
    'adventure seeker',
    'adventurous spirit',
    'wanderlust',
    'nomadic',
    'nomadic life',
    'roaming',
    'roaming free',
    'untamed',
    'wild at heart',
    'free spirit',
    'freedom seeker',
    'escape artist',
    'runaway',
    'refugee',
    'fugitive',
    'outlaw',
    'rebel',
    'resistance fighter',
    'revolutionary',
    'insurgent',
    'guerrilla',
    'partisan',
    'mercenary',
    'adventurer for hire',
    'fortune seeker',
    'fame seeker',
    'glory seeker',
    'treasure seeker',
    'explorer',
    'pathfinder',
    'trailblazer',
    'pioneer',
    'discoverer',
    'conqueror',
    'victor',
    'champion',
    'warrior',
    'soldier',
    'fighter',
    'combatant',
    'gladiator',
    'duelist',
    'swordsman',
    'archer',
    'ranger',
    'scout',
    'tracker',
    'hunter',
    'predator',
    'pursuer',
    'chaser',
    'escaper',
    'runner',
    'climber',
    'swimmer',
    'diver',
    'sailor',
    'navigator',
    'pilot',
    'driver',
    'rider',
    'adventuring party',
    'crew',
    'band',
    'team',
    'alliance',
    'coalition',
    'fellowship',
    'brotherhood',
    'sisterhood',
    'camaraderie',
    'companionship',
    'friendship',
    'loyal friend',
    'trusted companion',
    'faithful ally',
    'true ally',
    'sworn brother',
    'sworn sister',
    'comrade',
    'partner',
    'sidekick',
    'henchman',
    'follower',
    'disciple',
    'apprentice',
    'student',
    'learner',
    'trainee',
    'recruit',
    'newcomer',
    'greenhorn',
    'veteran',
    'experienced fighter',
    'seasoned warrior',
    'hardened warrior',
    'battle-scarred',
    'combat experienced',
    'survival trained',
    'wilderness survival',
    'basic survival',
    'advanced survival',
    'urban survival',
    'jungle survival',
    'desert survival',
    'arctic survival',
    'maritime survival',
    'naval combat',
    'sword combat',
    'hand-to-hand combat',
    'armed combat',
    'unarmed combat',
    'battle royal',
    'gladiatorial combat',
    'tournament',
    'competition',
    'contest',
    'challenge duel',
    'friendly duel',
    'honorable duel',
    'death duel',
    'final duel',
    'epic duel',
    'legendary duel',
    'sword fight',
    'lightsaber duel',
    'magic duel',
    'psychic duel',
    'battle of wills',
    'clash of titans',
    'final battle',
    'climactic battle',
    'epic battle',
    'legendary battle',
    'battle royale',
    'warfare',
    'combat zone',
    'war zone',
    'conflict zone',
    'danger zone',
    'trouble zone',
    'disputed territory',
    'contested land',
    'frontier',
    'borderland',
    'wasteland',
    'badlands',
    'forgotten land',
    'unmapped territory',
    'uncharted territory',
    'new world',
    'strange land',
    'foreign land',
    'exotic land',
    'mysterious land',
    'enchanted land',
    'magical land',
    'fantasy land',
    'alternate land',
    'parallel land',
    'alternate world',
    'alien world',
    'distant world',
    'faraway world',
    'new continent',
    'undiscovered continent',
    'lost continent',
    'sunken continent',
    'floating island',
    'hidden island',
    'secret island',
    'uncharted island',
    'deserted island',
    'tropical island',
    'volcanic island',
    'crystal island',
  ],

  fantasy: [
    'fantasy',
    'magic',
    'magical',
    'wizard',
    'sorcery',
    'enchanted',
    'mythical',
    'creature',
    'dragon',
    'spell',
    'mystical',
    'realm',
    'kingdom',
    'quest',
    'epic',
    'legendary',
    'supernatural',
    'ancient',
    'prophecy',
    'power',
    'high fantasy',
    'epic fantasy',
    'urban fantasy',
    'dark fantasy',
    'grimdark',
    'sword and sorcery',
    'mythology',
    'fae',
    'elves',
    'dwarves',
    'necromancy',
    'runes',
    'worldbuilding',
    'chosen one',
    'magic school',
    'magic system',
    'portal fantasy',
    'fantasy romance',
    'medieval fantasy',
    'legend',
    'myth',
    'saga',
    'artefact',
    'enchantement',
    'royaume',
    'dragon rider',
    'sorcier',
    'sorciere',
    'creatures fantastiques',
    'dark lord',
    'heroic fantasy',
    'fantasy novel',
    'magical world',
    'fantasy world',
    'enchanted forest',
    'magical creatures',
    'fantastical beings',
    'magical powers',
    'spellcasting',
    'potion brewing',
    'enchanted objects',
    'magical artifacts',
    'cursed items',
    'blessed items',
    'magical heritage',
    'fantasy hero',
    'fantasy adventure',
    'fantasy quest',
    'magical journey',
    'enchanted journey',
    'mystical powers',
    'ancient magic',
    'forbidden magic',
    'dark magic',
    'light magic',
    'elemental magic',
    'nature magic',
    'blood magic',
    'soul magic',
    'chaos magic',
    'order magic',
    'dragon fire',
    'magical battle',
    'fantasy battle',
    'epic battle',
    'final showdown',
    'magical climax',
    'fantasy climax',
    'magical destiny',
    'chosen destiny',
    'fate and magic',
    'magical fate',
    'mystical realm',
    'enchanted realm',
    'magical kingdom',
    'fantasy land',
    'otherworldly',
    'parallel world',
    'alternate dimension',
    'magical dimension',
    'ethereal',
    'celestial',
    'divine',
    'godlike',
    'demigod',
    'immortal',
    'ageless',
    'timeless',
    'eternal being',
    'ancient being',
    'primordial',
    'primordial force',
    'primal energy',
    'primal magic',
    'original magic',
    'first magic',
    'forbidden knowledge',
    'forbidden power',
    'forbidden spell',
    'forbidden ritual',
    'forbidden transformation',
    'forbidden love',
    'forbidden fruit',
    'forbidden place',
    'forbidden realm',
    'forbidden dimension',
    'hidden dimension',
    'secret dimension',
    'lost dimension',
    'phantom dimension',
    'shadow dimension',
    'mirror world',
    'inverse world',
    'upside down world',
    'twilight realm',
    'liminal space',
    'in-between space',
    'threshold world',
    'boundary realm',
    'border realm',
    'wall between worlds',
    'gateway',
    'portal',
    'doorway',
    'passage',
    'tunnel',
    'corridor',
    'rift',
    'tear in reality',
    'reality tear',
    'dimensional tear',
    'space-time tear',
    'time rift',
    'temporal rift',
    'temporal anomaly',
    'temporal distortion',
    'time distortion',
    'time anomaly',
    'timeline convergence',
    'timeline merging',
    'timeline collapse',
    'timeline reboot',
    'timeline reset',
    'timeline branching',
    'branching timeline',
    'alternate timeline',
    'parallel timeline',
    'divergent timeline',
    'original timeline',
    'prime timeline',
    'sacred timeline',
    'corrupted timeline',
    'fractured timeline',
    'shattered timeline',
    'broken timeline',
    'damaged timeline',
    'damaged reality',
    'corrupted reality',
    'twisted reality',
    'warped reality',
    'distorted reality',
    'reality warping',
    'space warping',
    'spacetime warping',
    'dimensional warping',
    'magic warping',
    'enchantment warping',
    'spell warping',
    'curse warping',
    'curse spreading',
    'blight',
    'corruption',
    'contamination',
    'infection of magic',
    'magical plague',
    'mana plague',
    'magic sickness',
    'magic addiction',
    'magic withdrawal',
    'magic depletion',
    'mana depletion',
    'mana drain',
    'mana pool',
    'mana accumulation',
    'mana reservoir',
    'mana source',
    'mana node',
    'ley line',
    'ley nexus',
    'magical convergence',
    'convergence point',
    'power point',
    'power node',
    'nexus of power',
    'center of power',
    'heart of power',
    'core of power',
    'essence of power',
    'embodiment of power',
    'incarnation of power',
    'avatar of power',
    'vessel of power',
    'channel of power',
    'conduit of power',
    'gateway to power',
    'door to power',
    'key to power',
    'keeper of power',
    'guardian of power',
    'protector of power',
    'seeker of power',
    'wielder of power',
    'master of power',
    'lord of power',
    'prince of power',
    'king of magic',
    'emperor of magic',
    'god of magic',
    'goddess of magic',
    'divine magic',
    'holy magic',
    'sacred magic',
    'blessed magic',
    'sanctified magic',
    'corrupted magic',
    'dark magic',
    'black magic',
    'forbidden magic',
    'taboo magic',
    'shadowy magic',
    'hidden magic',
    'secret magic',
    'ancient magic',
    'primal magic',
    'wild magic',
    'chaotic magic',
    'unpredictable magic',
    'unstable magic',
    'volatile magic',
    'dangerous magic',
    'hazardous magic',
    'perilous magic',
    'risky magic',
    'gambling with magic',
  ],

  'science-fiction': [
    'science fiction',
    'sci-fi',
    'futuristic',
    'space',
    'alien',
    'robot',
    'technology',
    'advanced technology',
    'dystopian',
    'utopian',
    'time travel',
    'parallel universe',
    'cyberpunk',
    'post-apocalyptic',
    'android',
    'artificial intelligence',
    'ai',
    'genetic',
    'mutation',
    'extraterrestrial',
    'science fiction novel',
    'space opera',
    'hard science fiction',
    'soft science fiction',
    'military science fiction',
    'speculative fiction',
    'future',
    'futurism',
    'spaceship',
    'interstellar',
    'colonization',
    'planetary',
    'virtual reality',
    'nanotechnology',
    'biotech',
    'cyborg',
    'automation',
    'machine learning',
    'singularity',
    'clone',
    'space travel',
    'first contact',
    'alien invasion',
    'posthuman',
    'dystopia',
    'utopia',
    'anticipation',
    'retrofuturism',
    'time loop',
    'multiverse',
    'science fantasy',
    'sf',
    'future technology',
    'advanced civilization',
    'alien civilization',
    'space exploration',
    'cosmic adventure',
    'galactic empire',
    'space war',
    'interstellar war',
    'space battle',
    'futuristic city',
    'space station',
    'asteroid field',
    'black hole',
    'wormhole',
    'hyperspace',
    'faster than light',
    'laser weapon',
    'plasma weapon',
    'energy weapon',
    'mechanical being',
    'robotic civilization',
    'android uprising',
    'ai awakening',
    'consciousness transfer',
    'mind upload',
    'virtual world',
    'metaverse',
    'digital reality',
    'hacking',
    'cyber warfare',
    'genetic engineering',
    'human enhancement',
    'superhuman',
    'transhumanism',
    'neo humanity',
    'mutation creature',
    'alien creature',
    'alien lifeform',
    'extraterrestrial being',
    'space colonist',
    'space merchant',
    'space pirate',
    'intergalactic travel',
    'galaxy spanning',
    'universe spanning',
    'time paradox',
    'alternate timeline',
    'parallel earth',
    'dystopian future',
    'utopian future',
    'post-human',
    'singularity event',
    'technological singularity',
    'space opera epic',
    'space saga',
    'stellar journey',
    'cosmic journey',
    'universal journey',
    'intergalactic journey',
    'interdimensional journey',
    'transdimensional journey',
    'multidimensional journey',
    'quantum journey',
    'quantum physics',
    'quantum mechanics',
    'quantum entanglement',
    'quantum superposition',
    'quantum teleportation',
    'quantum computing',
    'quantum processor',
    'quantum ai',
    'superintelligence',
    'superintelligent ai',
    'godlike ai',
    'omniscient ai',
    'omnipotent ai',
    'all-powerful ai',
    'all-knowing ai',
    'benevolent ai',
    'malevolent ai',
    'neutral ai',
    'chaotic ai',
    'lawful ai',
    'rogue ai',
    'awakened ai',
    'sentient ai',
    'conscious ai',
    'self-aware ai',
    'sapient ai',
    'emergent consciousness',
    'emergent intelligence',
    'evolution of ai',
    'ai evolution',
    'ai advancement',
    'ai development',
    'ai creation',
    'ai uprising',
    'ai rebellion',
    'ai revolution',
    'ai takeover',
    'ai domination',
    'ai extinction',
    'extinction event',
    'extinction level event',
    'extinction scenario',
    'doomsday scenario',
    'apocalyptic scenario',
    'cataclysmic scenario',
    'catastrophic scenario',
    'end of civilization',
    'end of world',
    'end of humanity',
    'human extinction',
    'human annihilation',
    'total annihilation',
    'complete destruction',
    'total destruction',
    'planetary destruction',
    'planetary doom',
    'planetary extinction',
    'species extinction',
    'extinction timeline',
    'extinction path',
    'extinction risk',
    'extinction threat',
    'existential risk',
    'existential threat',
    'existential danger',
    'existential crisis',
    'existential horror',
    'existential dread',
    'cosmic horror',
    'cosmic dread',
    'cosmic perspective',
    'vast universe',
    'infinite universe',
    'endless universe',
    'unknowable universe',
    'mysterious universe',
    'dark universe',
    'hostile universe',
    'cold universe',
    'uncaring universe',
    'indifferent universe',
    'alien universe',
    'strange universe',
    'bizarre universe',
    'surreal universe',
    'dreamlike universe',
    'nightmare universe',
    'hellscape',
    'wasteland',
    'barren landscape',
    'desolate landscape',
    'lifeless planet',
    'dead world',
    'dying world',
    'corrupted world',
    'infected world',
    'plague world',
    'cursed world',
    'doomed world',
    'abandoned world',
    'forgotten world',
    'lost world',
    'hidden world',
    'secret world',
    'underground world',
    'subterranean world',
    'underwater world',
    'aquatic world',
    'oceanic world',
    'deep sea world',
    'alien ocean',
    'methane ocean',
    'diamond ocean',
    'lava ocean',
    'blood ocean',
    'acid ocean',
    'toxic ocean',
    'boiling ocean',
    'frozen ocean',
    'crystal ocean',
    'luminescent ocean',
    'bioluminescent',
    'phosphorescent',
    'glowing',
    'radiating',
    'pulsing',
    'vibrating',
    'humming',
    'resonating',
    'frequency',
    'wavelength',
    'signal',
    'transmission',
    'broadcast',
    'communication',
    'messaging',
    'telepathy',
    'telekinesis',
    'psychic powers',
    'mental powers',
    'brain powers',
    'consciousness expansion',
    'dimensional awareness',
  ],

  mystère: [
    'mystery',
    'puzzle',
    'clue',
    'detective',
    'investigation',
    'crime',
    'secret',
    'hidden',
    'unknown',
    'suspicious',
    'conspiracy',
    'murder mystery',
    'whodunit',
    'enigma',
    'riddle',
    'evidence',
    'suspect',
    'revelation',
    'twist',
    'confession',
    'mystery fiction',
    'detective fiction',
    'crime fiction',
    'private investigator',
    'police procedural',
    'cold case',
    'forensic',
    'investigator',
    'interrogation',
    'alibi',
    'witness',
    'crime scene',
    'true crime inspired',
    'locked room mystery',
    'cozy mystery',
    'amateur sleuth',
    'missing person',
    'disappearance',
    'blackmail',
    'betrayal',
    'secret society',
    'twists and turns',
    'murder investigation',
    'who done it',
    'investigation criminelle',
    'roman policier',
    'intrigue',
    'indice',
    'suspicion',
    'mystere',
    'detective novel',
    'case file',
    'mysterious death',
    'unsolved crime',
    'cryptic clue',
    'mysterious disappearance',
    'detective work',
    'criminal investigation',
    'detective story',
    'mystery puzzle',
    'puzzle solving',
    'mystery solving',
    'detective agency',
    'mystery agency',
    'detective team',
    'investigative team',
    'crime solver',
    'mystery solver',
    'detective protagonist',
    'mystery protagonist',
    'criminal mind',
    'criminal psychology',
    'forensic science',
    'crime analysis',
    'evidence gathering',
    'witness testimony',
    'interrogation scene',
    'mystery unfolds',
    'mystery revealed',
    'plot twist mystery',
    'shocking revelation',
    'unexpected twist',
    'hidden truth',
    'concealed evidence',
    'secret motive',
    'hidden identity',
    'mistaken identity',
    'case closed',
    'mystery solved',
    'detective conclusion',
    'final revelation',
    'truth revealed',
    'killer revealed',
    'culprit revealed',
    'criminal revealed',
    'perpetrator identified',
    'perpetrator caught',
    'justice served',
    'killer caught',
    'criminal caught',
    'criminal apprehended',
    'criminal arrested',
    'criminal sentenced',
    'criminal executed',
    'criminal imprisoned',
    'criminal escaped',
    'criminal at large',
    'fugitive detective',
    'fugitive from law',
    'outlaw detective',
    'rogue detective',
    'corrupt detective',
    'morally grey detective',
    'anti-hero detective',
    'detective gone rogue',
    'detective betrayal',
    'detective conflict',
    'internal conflict',
    'personal case',
    'personal vendetta',
    'revenge case',
    'revenge investigation',
    'seeking justice',
    'quest for justice',
    'justice denied',
    'injustice',
    'wrongful conviction',
    'innocent accused',
    'false accusation',
    'frame job',
    'setup',
    'planted evidence',
    'false evidence',
    'fabricated evidence',
    'tampered evidence',
    'evidence tampering',
    'witness intimidation',
    'witness protection',
    'witness murdered',
    'witness disappeared',
    'witness silenced',
    'witness threatened',
    'witness paid off',
    'witness lies',
    'perjury',
    'lying witness',
    'unreliable witness',
    'credible witness',
    'key witness',
    'surprise witness',
    'unknown witness',
    'secret witness',
    'anonymous witness',
    'masked witness',
    'hidden identity witness',
    'witness protection program',
    'underground witness',
    'reluctant witness',
    'unwilling witness',
    'forced witness',
    'coerced witness',
    'manipulated witness',
    'deceived witness',
    'confused witness',
    'mistaken witness',
    'false memory witness',
    'memory implant',
    'memory manipulation',
    'mind control witness',
    'brainwashed witness',
    'hypnotized witness',
    'under hypnosis',
    'post-hypnotic suggestion',
    'subliminal message',
    'hidden message',
    'coded message',
    'secret code',
    'cipher',
    'decryption',
    'cryptography',
    'codebreaker',
    'cryptanalyst',
    'code-cracking',
    'puzzle-solving',
    'pattern recognition',
    'logical deduction',
    'deductive reasoning',
    'inductive reasoning',
    'abductive reasoning',
    'detective instinct',
    'gut feeling',
    'intuition',
    'detective intuition',
    'observational skills',
    'detective observation',
    'meticulous',
    'thorough investigation',
    'painstaking investigation',
    'detailed examination',
  ],

  thriller: [
    'thriller',
    'suspense',
    'suspenseful',
    'tension',
    'intense',
    'dangerous',
    'perilous',
    'threat',
    'risk',
    'chase',
    'escape',
    'plot twist',
    'shocking',
    'breathtaking',
    'page-turner',
    'unputdownable',
    'edge of your seat',
    'climax',
    'action packed',
    'pulse pounding',
    'psychological thriller',
    'crime thriller',
    'legal thriller',
    'spy thriller',
    'political thriller',
    'medical thriller',
    'techno thriller',
    'conspiracy thriller',
    'action thriller',
    'cat and mouse',
    'manhunt',
    'high stakes',
    'race against time',
    'hostage',
    'kidnapping',
    'assassin',
    'undercover',
    'espionage',
    'black ops',
    'intelligence',
    'double life',
    'sleeper agent',
    'revenge thriller',
    'mind game',
    'twisty thriller',
    'roman a suspense',
    'thriller psychologique',
    'course poursuite',
    'pression',
    'urgent',
    'cliffhanger',
    'thrilling action',
    'intense action',
    'high-octane',
    'adrenaline rush',
    'heart pounding',
    'nerve-wracking',
    'nail-biting',
    'tension filled',
    'suspenseful narrative',
    'gripping thriller',
    'compelling thriller',
    'thriller protagonist',
    'protagonist in danger',
    'life or death',
    'dangerous antagonist',
    'villainous threat',
    'moral dilemma',
    'impossible choice',
    'desperate situation',
    'survival instinct',
    'thriller climax',
    'thriller tension',
    'thriller pace',
    'fast-paced thriller',
    'relentless pursuit',
    'constant threat',
    'mounting danger',
    'escalating tension',
    'thriller twist',
    'unexpected turn',
    'shocking development',
    'thriller revelation',
    'hidden danger',
    'concealed threat',
    'betrayal thriller',
    'trust broken',
    'deception thriller',
    'manipulation thriller',
    'psychological game',
    'mental warfare',
    'cat and mouse game',
    'hunter and hunted',
    'thriller showdown',
    'final confrontation',
    'ultimate threat',
    'doomsday scenario',
    'countdown',
    'time running out',
    'time limit',
    'deadline',
    'deadline approaching',
    'time bomb',
    'ticking clock',
    'ticking timer',
    'pressure mounting',
    'pressure increasing',
    'stress increasing',
    'anxiety escalating',
    'fear escalating',
    'panic rising',
    'desperation rising',
    'hope fading',
    'salvation in sight',
    'last minute rescue',
    'narrow escape',
    'close call',
    'barely made it',
    'last second',
    'last moment',
    'final moment',
    'final second',
    'ultimate moment',
    'crucial moment',
    'pivotal moment',
    'turning point',
    'point of no return',
    'crossing the line',
    'crossing the Rubicon',
    'no turning back',
    'committed to the course',
    'locked in',
    'committed to action',
    'action committed',
    'deed done',
    'cannot be undone',
    'irreversible',
    'permanent consequences',
    'lasting consequences',
    'life-altering',
    'life-changing',
    'fate-changing',
    'destiny-changing',
    'world-changing',
    'paradigm shift',
    'reality shift',
    'truth shift',
    'perspective shift',
    'changed perspective',
    'new understanding',
    'hidden truth revealed',
    'hidden agenda revealed',
    'hidden conspiracy',
    'hidden war',
    'hidden conflict',
    'hidden enemy',
    'enemy revealed',
    'secret enemy',
    'unknown enemy',
    'mysterious enemy',
    'shadowy enemy',
    'faceless enemy',
    'masked enemy',
    'unidentified enemy',
    'unseen enemy',
    'invisible threat',
    'intangible threat',
    'unstoppable threat',
    'insurmountable threat',
    'overwhelming threat',
    'immense threat',
    'titanic threat',
    'colossal threat',
    'monumental threat',
    'existential threat',
    'ultimate threat',
    'final threat',
    'last threat',
    'greatest threat',
    'worst threat',
    'deadliest threat',
    'most dangerous threat',
    'most perilous threat',
    'most hazardous threat',
    'most critical threat',
    'critical situation',
    'critical juncture',
    'critical threshold',
    'crisis point',
    'crisis moment',
    'critical decision',
    'fateful decision',
    'world-defining decision',
    'life-defining decision',
    'morality test',
    'moral test',
    'ethical test',
    'character test',
    'character breaking',
    'character building',
    'character development',
    'character transformation',
    'personal growth',
    'personal struggle',
    'internal struggle',
    'internal conflict',
    'self vs self',
    'inner demons',
    'personal demons',
    'fighting demons',
    'exorcising demons',
    'traumatic past',
    'dark past',
    'shadowy past',
    'secret past',
    'hidden past',
    'mysterious past',
    'mysterious origins',
    'unknown origins',
    'obscure origins',
    'unclear origins',
    'forgotten origins',
    'erased origins',
    'fabricated origins',
    'false origins',
    'mistaken identity origins',
    'wrong identity',
    'false identity',
    'assumed identity',
    'stolen identity',
    'borrowed identity',
    'fake identity',
    'cover identity',
  ],
};

// Livres d'exemple pour chaque catégorie avec ISBN-13 valides OpenLibrary
const BOOKS_BY_CATEGORY: Record<
  string,
  Array<{
    name: string;
    author: string;
    description: string;
    isbn: string;
    publishingHouse: string;
    publishedAt: Date;
  }>
> = {
  horreur: [
    {
      name: 'The Shining',
      author: 'Stephen King',
      description:
        "Un homme, sa femme et son fils passent l'hiver isolés dans un hôtel montagneux hanté par des forces surnaturelles.",
      isbn: '9780385121675',
      publishingHouse: 'Doubleday',
      publishedAt: new Date('1977-01-28'),
    },
    {
      name: 'It',
      author: 'Stephen King',
      description:
        "Un groupe d'enfants fait face à une créature ancienne et maléfique qui hante leur ville.",
      isbn: '9780670813025',
      publishingHouse: 'Viking Press',
      publishedAt: new Date('1986-09-15'),
    },
    {
      name: 'The Exorcist',
      author: 'William Peter Blatty',
      description:
        "Le combat entre le bien et le mal lorsqu'une jeune fille est possédée par un démon.",
      isbn: '9780061785009',
      publishingHouse: 'Harper & Row',
      publishedAt: new Date('1971-05-01'),
    },
    {
      name: 'The Ring',
      author: 'Koji Suzuki',
      description:
        'Une cassette vidéo maudite qui tue quiconque la regarde sept jours plus tard.',
      isbn: '9780062059529',
      publishingHouse: 'Shogakukan',
      publishedAt: new Date('1991-01-01'),
    },
    {
      name: 'The Haunting of Hill House',
      author: 'Shirley Jackson',
      description:
        'Une équipe de chercheurs explore une maison maudite et découvre des phénomènes terrifiants.',
      isbn: '9781405280273',
      publishingHouse: 'Viking Press',
      publishedAt: new Date('1959-10-01'),
    },
    {
      name: 'The Bloody Chamber',
      author: 'Angela Carter',
      description:
        'Des contes de fées sinistres et sensuelstransformés en histoires sombres et envoûtantes.',
      isbn: '9780141162929',
      publishingHouse: 'Harper & Row',
      publishedAt: new Date('1979-06-08'),
    },
    {
      name: 'House of Leaves',
      author: 'Mark Z. Danielewski',
      description:
        'Un voyage labyrinthique dans une maison impossible qui défie les lois de la physique.',
      isbn: '9780375707469',
      publishingHouse: 'Pantheon Books',
      publishedAt: new Date('2000-03-02'),
    },
    {
      name: 'Mexican Gothic',
      author: 'Silvia Moreno-Garcia',
      description:
        "Une jeune femme découvre les secrets sombres d'une vieille mansarda gothique au Mexique.",
      isbn: '9780374204891',
      publishingHouse: 'Del Rey',
      publishedAt: new Date('2015-06-30'),
    },
  ],
  romance: [
    {
      name: 'Pride and Prejudice',
      author: 'Jane Austen',
      description:
        "L'histoire d'Elisabeth Bennet et de M. Darcy, deux âmes fortes qui découvrent l'amour au-delà de leurs préjugés.",
      isbn: '9780141439518',
      publishingHouse: 'T. Egerton',
      publishedAt: new Date('1813-01-28'),
    },
    {
      name: 'The Notebook',
      author: 'Nicholas Sparks',
      description:
        "Une histoire d'amour intemporelle entre deux personnes séparées par les classes sociales.",
      isbn: '9780553210583',
      publishingHouse: 'Warner Books',
      publishedAt: new Date('1996-10-01'),
    },
    {
      name: 'Outlander',
      author: 'Diana Gabaldon',
      description:
        "Une femme du 20e siècle voyage dans le temps et tombe amoureuse d'un guerrier écossais au 18e siècle.",
      isbn: '9780385295955',
      publishingHouse: 'Delacorte Press',
      publishedAt: new Date('1991-06-01'),
    },
    {
      name: "The Time Traveler's Wife",
      author: 'Audrey Niffenegger',
      description:
        'Un homme qui voyage involontairement dans le temps et sa relation complexe avec sa femme.',
      isbn: '9780385333126',
      publishingHouse: 'Scribner',
      publishedAt: new Date('2003-09-30'),
    },
    {
      name: 'Me Before You',
      author: 'Jojo Moyes',
      description:
        "Une jeune femme devient l'assistante d'un homme paralysé, ce qui crée une connexion inattendue.",
      isbn: '9780143124542',
      publishingHouse: 'Penguin Press',
      publishedAt: new Date('2012-01-01'),
    },
    {
      name: 'The Fault in Our Stars',
      author: 'John Green',
      description:
        "Deux jeunes gens atteints du cancer se rencontrent et vivent une histoire d'amour transformatrice.",
      isbn: '9780141349496',
      publishingHouse: 'Dutton',
      publishedAt: new Date('2012-01-10'),
    },
    {
      name: 'A Walk to Remember',
      author: 'Nicholas Sparks',
      description:
        "Un jeune homme tombe amoureux d'une fille pieuse et leur amour change à jamais sa vision de la vie.",
      isbn: '9780553294452',
      publishingHouse: 'Warner Books',
      publishedAt: new Date('1999-10-01'),
    },
    {
      name: 'Jane Eyre',
      author: 'Charlotte Brontë',
      description:
        "Une gouvernante sans fortune découvre l'amour vrai avec un homme mystérieux et complexe.",
      isbn: '9780141441146',
      publishingHouse: 'Smith, Elder & Co.',
      publishedAt: new Date('1847-10-16'),
    },
  ],
  aventure: [
    {
      name: 'The Adventures of Sherlock Holmes',
      author: 'Arthur Conan Doyle',
      description:
        'Les aventures du détective le plus célèbre du monde et de son ami Watson.',
      isbn: '9780141439686',
      publishingHouse: 'George Newnes',
      publishedAt: new Date('1892-10-14'),
    },
    {
      name: 'Treasure Island',
      author: 'Robert Louis Stevenson',
      description:
        'Un jeune garçon embarque dans une quête périlleuse pour trouver un trésor caché.',
      isbn: '9780141435886',
      publishingHouse: 'Cassell & Co.',
      publishedAt: new Date('1881-11-14'),
    },
    {
      name: 'Journey to the Center of the Earth',
      author: 'Jules Verne',
      description:
        'Une expédition extraordinaire au cœur de la Terre remplie de dangers et de découvertes.',
      isbn: '9780141439953',
      publishingHouse: 'Pierre-Jules Hetzel',
      publishedAt: new Date('1864-11-25'),
    },
    {
      name: 'The Count of Monte Cristo',
      author: 'Alexandre Dumas',
      description:
        "Un homme injustement emprisonné s'échappe et se venge spectaculairement de ses ennemis.",
      isbn: '9780141449301',
      publishingHouse: 'Journal des Débats',
      publishedAt: new Date('1844-08-28'),
    },
    {
      name: 'The Three Musketeers',
      author: 'Alexandre Dumas',
      description:
        "Les aventures d'un jeune homme et de trois mousquetaires dans la France du 17e siècle.",
      isbn: '9780141439617',
      publishingHouse: 'Le Siècle',
      publishedAt: new Date('1844-03-14'),
    },
    {
      name: 'Around the World in Eighty Days',
      author: 'Jules Verne',
      description:
        'Un riche excentrique relève le pari de faire le tour du monde en quatre-vingts jours.',
      isbn: '9780141441146',
      publishingHouse: 'Le Temps',
      publishedAt: new Date('1873-11-06'),
    },
    {
      name: 'The Adventures of Tom Sawyer',
      author: 'Mark Twain',
      description:
        "Les aventures espièg les d'un jeune garçon au bord du Mississippi au 19e siècle.",
      isbn: '9780141391748',
      publishingHouse: 'American Publishing Company',
      publishedAt: new Date('1876-12-09'),
    },
    {
      name: 'Robinson Crusoe',
      author: 'Daniel Defoe',
      description:
        'Un marin naufragé survit seul sur une île déserte pendant vingt-huit ans.',
      isbn: '9780141439228',
      publishingHouse: 'W. Taylor',
      publishedAt: new Date('1719-04-25'),
    },
  ],
  fantasy: [
    {
      name: 'The Lord of the Rings: The Fellowship of the Ring',
      author: 'J.R.R. Tolkien',
      description:
        'Une quête épique pour détruire un anneau magique et sauver le monde de la domination du mal.',
      isbn: '9780544003415',
      publishingHouse: 'Allen & Unwin',
      publishedAt: new Date('1954-07-29'),
    },
    {
      name: "Harry Potter and the Philosopher's Stone",
      author: 'J.K. Rowling',
      description:
        'Un jeune sorcier découvre un monde magique caché et fait face aux menaces du mal.',
      isbn: '9780747532699',
      publishingHouse: 'Bloomsbury',
      publishedAt: new Date('1997-06-26'),
    },
    {
      name: 'A Game of Thrones',
      author: 'George R.R. Martin',
      description:
        "Un monde fantasy complexe rempli d'intrigues politiques, de magie et de dragons.",
      isbn: '9780553103541',
      publishingHouse: 'Bantam Books',
      publishedAt: new Date('1996-08-06'),
    },
    {
      name: 'The Name of the Wind',
      author: 'Patrick Rothfuss',
      description:
        "L'histoire d'un magicien légendaire racontée par lui-même dans un monde époustouflant.",
      isbn: '9780575081482',
      publishingHouse: 'DAW Books',
      publishedAt: new Date('2007-08-29'),
    },
    {
      name: 'The Way of Kings',
      author: 'Brandon Sanderson',
      description:
        'Une épopée fantasy sur des guerriers, la magie et le destin dans un monde magnifique.',
      isbn: '9780765326355',
      publishingHouse: 'Tor Books',
      publishedAt: new Date('2010-08-31'),
    },
    {
      name: 'The Cruel Prince',
      author: 'Holly Black',
      description:
        'Une jeune fille grandit parmi les créatures féériques du Monde de Féerie.',
      isbn: '9781250195449',
      publishingHouse: 'Greenwillow Books',
      publishedAt: new Date('2018-01-02'),
    },
    {
      name: 'Six of Crows',
      author: 'Leigh Bardugo',
      description:
        'Un groupe de criminels tente un héist impossible pour devenir riches et légendaires.',
      isbn: '9780545284837',
      publishingHouse: 'Balzer + Bray',
      publishedAt: new Date('2015-09-29'),
    },
    {
      name: 'Mistborn: The Final Empire',
      author: 'Brandon Sanderson',
      description:
        'Une jeune fille découvre des pouvoirs magiques cachés dans un empire totalitaire.',
      isbn: '9780765311788',
      publishingHouse: 'Tor Books',
      publishedAt: new Date('2006-07-17'),
    },
  ],
  'science-fiction': [
    {
      name: 'Dune',
      author: 'Frank Herbert',
      description:
        "Une épopée spatiale sur la politique, la religion et l'écologie sur une planète désertique.",
      isbn: '9780441172719',
      publishingHouse: 'Ace Books',
      publishedAt: new Date('1965-06-01'),
    },
    {
      name: '1984',
      author: 'George Orwell',
      description:
        'Un roman dystopique sur un régime totalitaire contrôlant chaque aspect de la vie humaine.',
      isbn: '9780451524935',
      publishingHouse: 'Secker & Warburg',
      publishedAt: new Date('1949-06-08'),
    },
    {
      name: 'The Martian',
      author: 'Andy Weir',
      description:
        'Un astronaute stranded sur Mars utilise son ingéniosité pour survivre et trouver son chemin de retour.',
      isbn: '9780553418026',
      publishingHouse: 'Crown Publishers',
      publishedAt: new Date('2011-11-11'),
    },
    {
      name: 'Foundation',
      author: 'Isaac Asimov',
      description:
        "Un scientifique utilise la psychohistoire pour prédire l'avenir et sauver la civilisation.",
      isbn: '9780553294384',
      publishingHouse: 'Gnome Press',
      publishedAt: new Date('1951-06-01'),
    },
    {
      name: 'Neuromancer',
      author: 'William Gibson',
      description:
        'Un hacker cyberpunk est engagé pour une dernière mission dans un futur dystopique.',
      isbn: '9780441569595',
      publishingHouse: 'Ace Books',
      publishedAt: new Date('1984-07-01'),
    },
    {
      name: 'The Expanse: Leviathan Wakes',
      author: 'James S.A. Corey',
      description:
        'Un détective privé et un capitaine de vaisseau enquêtent sur une disparition qui risque de déclencher une guerre spatiale.',
      isbn: '9780316129083',
      publishingHouse: 'Orbit',
      publishedAt: new Date('2011-06-14'),
    },
    {
      name: 'Altered Carbon',
      author: 'Richard K. Morgan',
      description:
        "Un assassin ressuscité dans un corps neuf doit résoudre le meurtre d'un homme riche dans un futur dystopique.",
      isbn: '9780425089577',
      publishingHouse: 'Del Rey',
      publishedAt: new Date('2002-11-19'),
    },
    {
      name: 'The Ministry for the Future',
      author: 'Kim Stanley Robinson',
      description:
        "Un regard futuriste sur comment l'humanité pourrait affronter la crise climatique.",
      isbn: '9780316300130',
      publishingHouse: 'Hachette Book Group',
      publishedAt: new Date('2020-10-06'),
    },
  ],
  mystère: [
    {
      name: 'The Girl with the Dragon Tattoo',
      author: 'Stieg Larsson',
      description:
        "Un journaliste et une hacker brillante enquêtent sur la disparition d'une femme riche.",
      isbn: '9780307454546',
      publishingHouse: 'Norstedts & Söner',
      publishedAt: new Date('2005-08-01'),
    },
    {
      name: 'The Da Vinci Code',
      author: 'Dan Brown',
      description:
        'Un symbologiste et une cryptographe résolvent un mystère ancien lié aux secrets religieux.',
      isbn: '9780385504205',
      publishingHouse: 'Doubleday',
      publishedAt: new Date('2003-03-18'),
    },
    {
      name: 'Murder on the Orient Express',
      author: 'Agatha Christie',
      description:
        'Le détective Hercule Poirot enquête sur un meurtre dans un train luxueux bloqué dans la neige.',
      isbn: '9780062079570',
      publishingHouse: "Christie's Estate",
      publishedAt: new Date('1934-01-01'),
    },
    {
      name: 'And Then There Were None',
      author: 'Agatha Christie',
      description:
        'Dix étrangers sont piégés sur une île et tués un par un selon une comptine mystérieuse.',
      isbn: '9780062073556',
      publishingHouse: "Christie's Estate",
      publishedAt: new Date('1939-11-06'),
    },
    {
      name: 'The Big Sleep',
      author: 'Raymond Chandler',
      description:
        'Le détective privé Philip Marlowe enquête sur le chantage et le meurtre à Los Angeles.',
      isbn: '9780141184234',
      publishingHouse: 'Knopf',
      publishedAt: new Date('1939-02-06'),
    },
    {
      name: 'Mystic River',
      author: 'Dennis Lehane',
      description:
        'Trois enfants liés par un traumatisme se retrouvent adultes confrontés à des crimes qui changent à jamais leurs vies.',
      isbn: '9780380731596',
      publishingHouse: 'William Morrow',
      publishedAt: new Date('2001-05-28'),
    },
    {
      name: 'The Girl Before',
      author: 'JP Delaney',
      description:
        'Une jeune femme emménage dans un appartement futuriste et commence à revivre les mystères liés à sa locataire précédente.',
      isbn: '9780345415298',
      publishingHouse: 'Ballantine Books',
      publishedAt: new Date('2016-10-04'),
    },
    {
      name: 'The Woman in Cabin 10',
      author: 'Ruth Ware',
      description:
        "Une journaliste en croisière découvre une femme mystérieuse et sa cabine devient la scène d'un crime.",
      isbn: '9780804170734',
      publishingHouse: 'The Random House Publishing Group',
      publishedAt: new Date('2016-08-02'),
    },
  ],
  thriller: [
    {
      name: 'The Silence of the Lambs',
      author: 'Thomas Harris',
      description:
        "Une jeune agent du FBI demande l'aide d'un tueur en série emprisonné pour attraper un autre tueur.",
      isbn: '9780312927579',
      publishingHouse: "St. Martin's Press",
      publishedAt: new Date('1988-06-01'),
    },
    {
      name: 'The Girl on the Train',
      author: 'Paula Hawkins',
      description:
        "Une femme devient témoin d'un incident troublant depuis son train et se retrouve entraînée dans un mystère dangereux.",
      isbn: '9780345457011',
      publishingHouse: 'Doubleday',
      publishedAt: new Date('2015-01-13'),
    },
    {
      name: 'Gone Girl',
      author: 'Gillian Flynn',
      description:
        "Le mari d'une femme disparue devient suspect dans une affaire d'enlèvement remplie de rebondissements.",
      isbn: '9780307588371',
      publishingHouse: 'Crown Publishers',
      publishedAt: new Date('2012-06-27'),
    },
    {
      name: 'The Bourne Identity',
      author: 'Robert Ludlum',
      description:
        "Un homme amnésique découvre qu'il est un agent secret et doit fuir pour sa vie.",
      isbn: '9780553275957',
      publishingHouse: 'Random House',
      publishedAt: new Date('1980-03-01'),
    },
    {
      name: 'The Woman in White',
      author: 'Wilkie Collins',
      description:
        'Un mystère gothique où une jeune femme innocente est remplacée par une impostrice en clinique.',
      isbn: '9780141439594',
      publishingHouse: 'All the Year Round',
      publishedAt: new Date('1859-11-26'),
    },
    {
      name: 'In the Woods',
      author: 'Tana French',
      description:
        "Un détective enquête sur un meurtre qui le ramène à ses propres traumatismes d'enfance.",
      isbn: '9780340899779',
      publishingHouse: 'Hodder & Stoughton',
      publishedAt: new Date('2007-03-01'),
    },
    {
      name: 'Rebecca',
      author: 'Daphne du Maurier',
      description:
        'Une jeune femme épouse un riche aristocrate anglais, mais découvre que le fantôme de sa première épouse hante le château.',
      isbn: '9780141040685',
      publishingHouse: 'Victor Gollancz Ltd',
      publishedAt: new Date('1938-08-03'),
    },
    {
      name: 'The Kind Worth Killing',
      author: 'Peter Swanson',
      description:
        'Deux étrangers se rencontrent en avion et nouent une amitié dangereuse basée sur la vengeance mutuelle.',
      isbn: '9780062267597',
      publishingHouse: 'William Morrow',
      publishedAt: new Date('2015-02-10'),
    },
  ],
};

async function seed() {
  console.log('🌱 Début du seeding...\n');

  try {
    // Verify and create categories one by one (idempotent)
    console.log('📚 Création des catégories...');
    let createdCategories = 0;
    for (const cat of CATEGORIES) {
      const [existingCategory] = await db
        .select({ id: category.id })
        .from(category)
        .where(eq(category.name, cat.name));

      if (existingCategory) {
        continue;
      }

      await db.insert(category).values(cat);
      createdCategories++;
      console.log(`  ✅ Catégorie créée: ${cat.name}`);
    }
    if (createdCategories === 0) {
      console.log('  ⏭️  Toutes les catégories existent déjà');
    }

    // Récupérer les catégories avec leurs IDs
    const allCategories = await db.select().from(category);
    const categoryMap = new Map(allCategories.map((c) => [c.name, c.id]));

    // Create keywords per category (idempotent)
    console.log('\n🔑 Création des keywords...');
    let createdKeywordCount = 0;
    for (const [catName, baseKeywords] of Object.entries(
      KEYWORDS_BY_CATEGORY,
    )) {
      const catId = categoryMap.get(catName);
      if (!catId) {
        console.log(`  ❌ Catégorie ${catName} non trouvée`);
        continue;
      }

      const candidateKeywords = baseKeywords.map((kw) => kw.trim());
      const normalizedCandidates = Array.from(
        new Set(candidateKeywords.map((kw) => kw.toLowerCase())),
      );

      const existingForCategory = await db
        .select({ name: keyword.name })
        .from(keyword)
        .where(eq(keyword.categoryId, catId));
      const existingSet = new Set(
        existingForCategory.map((k) => k.name.toLowerCase()),
      );

      let createdForCategory = 0;
      for (const kw of normalizedCandidates) {
        if (existingSet.has(kw)) continue;

        await db.insert(keyword).values({
          name: kw,
          categoryId: catId,
        });
        createdKeywordCount++;
        createdForCategory++;
      }

      if (createdForCategory > 0) {
        console.log(
          `  ✅ ${createdForCategory} keywords ajoutés pour ${catName}`,
        );
      } else {
        console.log(`  ⏭️  Aucun nouveau keyword pour ${catName}`);
      }
    }
    console.log(`  📊 Total nouveaux keywords: ${createdKeywordCount}`);

    // Create books per category based on ISBN uniqueness (idempotent)
    console.log('\n📖 Création des livres...');
    let createdBookCount = 0;
    for (const [catName, books] of Object.entries(BOOKS_BY_CATEGORY)) {
      const catId = categoryMap.get(catName);
      if (!catId) {
        console.log(`  ❌ Catégorie ${catName} non trouvée`);
        continue;
      }

      let createdForCategory = 0;
      for (const b of books) {
        const [existingBook] = await db
          .select({ id: book.id })
          .from(book)
          .where(eq(book.isbn, b.isbn));

        if (existingBook) {
          continue;
        }

        await db.insert(book).values({
          name: b.name,
          cover_url: coverFromIsbn(b.isbn),
          author: b.author,
          description: b.description,
          isbn: b.isbn,
          publishingHouse: b.publishingHouse,
          publishedAt: b.publishedAt.toISOString().slice(0, 10),
          categoryId: catId,
        });
        createdBookCount++;
        createdForCategory++;
      }

      if (createdForCategory > 0) {
        console.log(
          `  ✅ ${createdForCategory} livres ajoutés pour ${catName}`,
        );
      } else {
        console.log(`  ⏭️  Aucun nouveau livre pour ${catName}`);
      }
    }
    console.log(`  📊 Total nouveaux livres: ${createdBookCount}`);

    console.log('\n✨ Seeding terminé avec succès!');
  } catch (error) {
    console.error('❌ Erreur lors du seeding:', error);
    process.exit(1);
  }
}

seed();
